name: gestion_financiere
description: "Application personnelle de gestion financière - Bénin"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Gestion d'état + Injection de dépendances
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.2.0

  # Base de données locale
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3     # nécessaire pour Windows/Linux/macOS
  path: ^1.9.0
  path_provider: ^2.1.3

  # Formatage devises / dates (utile pour le XOF et les autres devises)
  intl: ^0.20.2

  # Icônes modernes
  cupertino_icons: ^1.0.6

  # Graphiques (Bilans)
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
